### ISSUE TITLE
Mejoras

### ISSUE THREAD

**Issue by migueldelmazo** [Adalab/m3-evaluacion-intermedia-sara-ribera#1]
Hola @sara-ribera, quieres terminar el ejercicio antes de que te lo corrija?

**Comment by sara-ribera** [comment]
Hola Miguel, 

Sería genial poderlo acabar este fin de semana y entregartelo el lunes. 

Un millón de gracias por la oportunidad

Sara

**Comment by sara-ribera** [comment]
Hola Miguel, 
Acabo de terminar la evaluación intermedia.
Un saludo
